export type InfoSection = { id: string; title: string; paragraphs?: string[]; items?: string[]; ordered?: boolean; faq?: { question: string; answer: string }[] };
export type InfoContent = { title: string; description: string; sections: InfoSection[]; legal?: boolean };

export const operator = { email: 'support@32-plus.com', name: 'Promacan Corp, S.L.', taxId: 'B44599611', address: 'Calle Domingo Doreste 23, apartamento 15, 35110 Santa Lucía de Tirajana, Las Palmas, Spain' };
const roles = '32+ Night Rentals is operated by Promacan Corp, S.L. It provides the marketplace and acts as an intermediary. The property owner is the accommodation provider or landlord; the tenant is the person requesting and booking the temporary stay. The rental agreement is between the owner and tenant.';
const availability = 'Booking requests, owner review and digital signatures are available. Secure platform payments and direct messaging are not yet available. Do not treat an approved request or a recorded signature as confirmation that payment has been made.';
const verification = 'Listing approval does not guarantee a property, owner, tenant or the legal suitability of a rental. Check the property information, the scope of any stated verification and the agreement before committing.';

// TODO(business/legal): Confirm commercial-register particulars;
// approve final platform terms, formation of contracts, tax treatment, cancellation,
// refund and deposit rules. Confirm payment provider/onboarding/release conditions.
// TODO(privacy): Approve legal bases, retention schedule, hosting provider/region,
// processor contracts, international-transfer safeguards and cookie inventory,
// including Google Maps consent. No unverified specifics are published below.
export const infoPages: Record<string, InfoContent> = {
  about: {
    title: 'About 32+', description: 'Furnished homes for genuine temporary stays of 32 nights or longer.',
    sections: [
      { id: 'a-temporary-home', title: 'A temporary home, with a clearer process', paragraphs: ['32+ connects property owners with people who need furnished accommodation for at least 32 nights: for work, study, relocation or another genuine temporary purpose. It is a medium-term rental marketplace, not a holiday-rental platform or a traditional long-term letting agency.', 'Our aim is a simpler and more secure way to arrange a stay, with transparent pricing, verified information where checks are actually completed, digital agreements, secure payments and communication between tenants and owners through the platform.'] },
      { id: 'available-today', title: 'What you can do today', paragraphs: [availability, 'You can search homes, review conditions, submit a request and follow the agreement process in your dashboard. Payment and messaging steps will be explained when those services become available.'] },
      { id: 'clear-responsibilities', title: 'Clear responsibilities', paragraphs: [roles, verification] },
    ],
  },
  'how-it-works': {
    title: 'How It Works', description: 'From finding the right home to arranging the details of your temporary stay.',
    sections: [
      { id: 'tenants', title: 'For tenants', ordered: true, items: ['Search for a suitable furnished home for 32 nights or longer.', 'Review the property, total price, availability, deposit, rules and conditions.', 'Submit a booking request with your dates, guest count, temporary purpose and the required information.', 'After owner approval, review and sign the rental agreement. The current agreement remains a draft until the required identities, address and final terms are complete.', 'Pay securely through the platform when checkout becomes available. Check the full total before paying; payment is not collected by the current request flow.', 'Communicate with the owner through the platform when messaging becomes available. Your dashboard currently records request details and owner decision notes.', 'Once the agreement and payment arrangements are confirmed, arrange check-in, inspect the home and complete your stay under the agreed conditions.'] },
      { id: 'owners', title: 'For owners', ordered: true, items: ['Create a 32+ account. The same account can be used to rent a home and list a property.', 'Add your property and supply the information needed for listing review and any requested verification.', 'Set availability, rent, deposit, rules and rental conditions accurately.', 'Review booking requests, dates, occupants and the stated temporary purpose.', 'Approve a suitable tenant and sign the agreement. The tenant then reviews and signs it.', 'Receive payment according to the platform payout schedule once payment services are activated and verification is complete. A scheduled date in the dashboard is not evidence of a transfer.'] },
      { id: 'current-service', title: 'Before you make arrangements', paragraphs: [availability, verification] },
    ],
  },
  contact: { title: 'Contact', description: 'Tell us what you need help with, whether you are looking for a home or listing one.', sections: [{ id: 'before-you-send', title: 'Help us understand your enquiry', paragraphs: ['Include a property or request reference if relevant. Please do not send passwords, payment-card details, identification documents or medical records through this form.', 'For an immediate threat to safety, contact local emergency services. This form is not an emergency service.'] }] },
  'tenant-fees': { title: 'Tenant Fees', description: 'Understand your rent, service fee and other costs before you commit.', sections: [
    { id: 'service-fee', title: 'Your 32+ service fee', paragraphs: ['The tenant service fee is calculated on accommodation rent only. The current standard rate and an example are shown below. A property-specific pricing policy may apply; the quote for your request and its recorded fee are the figures to review.'] },
    { id: 'price-breakdown', title: 'What makes up the total?', items: ['Rent: the accommodation price for your dates. The pricing calculation uses each applicable monthly rent divided by 30 for each night, with the total rounded to cents.', 'Service fee: the 32+ tenant fee added to accommodation rent.', 'Deposit: a separate security amount if the owner requires one. It is not part of the service-fee calculation.', 'Other charges: cleaning, utilities or other agreed costs must be disclosed separately. Do not assume they are included in a rent-plus-service-fee quote.'], paragraphs: ['The full amount due, including any separately payable charges, must be shown before payment. The current request quote does not collect money. Review the listing and agreement and clarify any unclear charge before proceeding.'] },
  ] },
  'rental-requirements': { title: 'Rental Requirements', description: 'Prepare the information relevant to your property and the temporary purpose of your stay.', sections: [
    { id: 'possible-requirements', title: 'What you may be asked for', items: ['Valid identification.', 'Accurate contact information.', 'A genuine temporary reason for the stay.', 'Relevant evidence of income, employment, studies, medical treatment, relocation or another temporary purpose.', 'Payment details through the designated secure checkout, when available.', 'Acceptance and signature of the rental agreement.'], paragraphs: ['Requirements vary by property, owner and stage of the process. Every document listed here is not automatically mandatory. The initial request currently asks for dates, occupants and temporary-purpose information, rather than a full document pack.', 'Only provide information relevant to the request. Ask why a document is needed and how to share it securely; avoid sending sensitive medical details or identity documents through general enquiries.'] },
    { id: 'suitability', title: 'Check that the rental suits your needs', paragraphs: ['A stay must be at least 32 nights, or longer if the property specifies a higher minimum. Duration alone does not determine the legal classification of a rental. The owner and tenant must establish that the property, purpose and agreement are appropriate.', verification] },
  ] },
  payouts: { title: 'How Payouts Work', description: 'What the platform records today, and what must be in place before an owner receives funds.', sections: [
    { id: 'payment-status', title: 'Payment services are not yet available', paragraphs: ['The current service records booking prices, fee amounts and payment or payout statuses. It does not yet provide live checkout, payment collection or bank transfers. A pending payout or scheduled release in the dashboard does not mean money has been collected or sent.', 'No statement on this page means that 32+ itself holds regulated client funds. The payment provider, funds-handling arrangements and applicable protections will be identified before payment services are offered.'] },
    { id: 'fees', title: 'Tenant payment and platform fees', paragraphs: ['The pricing record adds the tenant service fee to accommodation rent and deducts the owner service fee from accommodation rent to calculate the owner net amount. Deposits and other disclosed charges are separate. A provider processing-cost field exists, but no live processing charge or settlement is implemented.'] },
    { id: 'timing', title: 'Owner payout timing', paragraphs: ['When an owner approves a request, the current workflow records a provisional release date one day after the move-in date. No automated payout executes on that date. Final release conditions and bank-arrival timing remain to be confirmed before activation.', 'Once enabled, settlement may depend on successful tenant payment, required verification, booking status and any dispute or review. Provider processing, banking days and bank checks may delay arrival; a release date is not a guaranteed receipt date.'] },
    { id: 'verification', title: 'Identity and bank-account verification', paragraphs: ['Owners will need to complete the identity and bank-account verification required by the selected payment provider before receiving payouts. The current application does not offer that onboarding flow. Do not send bank credentials or identity documents through the contact form.'] },
    { id: 'exceptions', title: 'Deposits, cancellations and disputes', paragraphs: ['A property may require a separate deposit. Its collection, deductions and return arrangements must be stated in the final agreement; there is no automated deposit holding or return process in the current service.', 'Listings support cancellation-policy labels, but an automated refund calculation and payment reversal process are not implemented. Ask for the applicable terms before committing. No universal refund amount, deadline or service-fee refund is promised here.', 'Report a cancellation, disputed charge or damage issue with the request reference and relevant evidence. Any eventual payment-provider review, refund or dispute can affect payout timing.'] },
  ] },
  help: { title: 'Help Centre', description: 'Answers to common questions about temporary rentals, accounts and your next steps.', sections: [
    { id: 'getting-started', title: 'Getting started', faq: [{ question: 'What is a 32+ stay?', answer: 'A furnished rental for a genuine temporary purpose lasting at least 32 nights. Some homes require longer stays. Browse Find a Home to review the available properties.' }] },
    { id: 'tenant-accounts', title: 'Tenant accounts and verification', faq: [{ question: 'What do I need to create an account?', answer: 'Use your name, email and a password. You may need to confirm your email. Property-specific information or verification may be requested later; not every supporting document is required for every request.' }] },
    { id: 'owner-accounts', title: 'Owner accounts and listings', faq: [{ question: 'Do I need a separate owner account?', answer: 'No. One account supports renting and listing. Sign in and select List your property in the dashboard. Keep photos, availability, prices and conditions accurate. Listing approval is not a legal or quality guarantee.' }] },
    { id: 'booking-requests', title: 'Booking requests', faq: [{ question: 'Is my home booked as soon as I send a request?', answer: 'No. The owner reviews your dates, guest count and temporary purpose. Approval, agreement completion and the applicable payment arrangements must follow. Check the request status in your dashboard.' }] },
    { id: 'payments-fees', title: 'Payments and fees', faq: [{ question: 'Where can I see the price?', answer: 'The request flow shows accommodation rent and the tenant service fee. Review deposit and other charges separately. The Tenant Fees page shows the current standard rate. Live checkout and payouts are not yet available.' }] },
    { id: 'agreements', title: 'Agreements', faq: [{ question: 'What does signing in my dashboard mean?', answer: 'The platform records signatures for the rental workflow. The current agreement remains a draft until identities, the exact address and final terms are complete. Read it carefully and raise any discrepancy before proceeding.' }] },
    { id: 'check-in', title: 'Check-in and stays', faq: [{ question: 'How should I prepare for arrival?', answer: 'Once the stay is confirmed, agree arrival and key arrangements with the owner. Check the inventory and condition on arrival and retain a record of any issue. Direct platform messaging is not yet available.' }] },
    { id: 'cancellations', title: 'Cancellations and refunds', faq: [{ question: 'Can I cancel and receive a refund?', answer: 'Check the specific terms disclosed for your rental and contact support with the request reference. Policy labels alone do not define a refund amount. Automated cancellations and refunds are not implemented, and this page does not promise a fixed entitlement or deadline.' }] },
    { id: 'deposits', title: 'Deposits and damages', faq: [{ question: 'Is the deposit a service fee?', answer: 'No. A deposit is a separate amount required by some owners. The final agreement must explain how it is handled and returned and how damage deductions are assessed. Keep an inventory and evidence of condition.' }] },
    { id: 'safety', title: 'Safety, disputes, and reporting a problem', faq: [{ question: 'How do I report a concern?', answer: 'Use Contact with the property or request reference and a clear description. Do not share passwords, card numbers or sensitive documents. For immediate danger, contact local emergency services. Listing approval does not guarantee safety or legal suitability.' }] },
  ] },
  terms: { title: 'Terms & Conditions', description: 'The roles, responsibilities and current scope of the 32+ marketplace.', legal: true, sections: [
    { id: 'operator', title: '1. Operator and scope', paragraphs: [roles, 'The operator’s identification and postal address appear below. These terms describe use of the marketplace; the specific rental conditions must also be agreed between the owner and tenant.'] },
    { id: 'temporary-stays', title: '2. Temporary stays and property suitability', paragraphs: ['The platform is intended for furnished stays of at least 32 nights for a genuine temporary purpose. It is not a holiday-rental platform or a traditional long-term letting agency. Owners are responsible for their authority to offer the property and for applicable property obligations; tenants must give accurate information about the intended use.', 'A 32-night minimum does not by itself establish a lawful rental category or replace applicable housing rules.', verification] },
    { id: 'accounts', title: '3. Accounts and acceptable use', paragraphs: ['Provide accurate information, protect your login credentials and use only content and property information you are entitled to provide. Do not impersonate another person, submit fraudulent requests, misuse personal information or interfere with the platform.', 'One account may be used as a tenant and an owner. Report suspected misuse through Contact.'] },
    { id: 'requests-agreements', title: '4. Requests and agreements', paragraphs: ['Submitting a request does not automatically reserve or confirm a stay. The owner reviews it and can approve or decline it. The workflow records owner and tenant signatures. The current agreement is a draft pending complete identities, the exact address and final terms.', 'Read the rental agreement, price and property conditions before signing. Do not assume that listing approval, a signature record or a dashboard status establishes that a payment has been completed.', availability] },
    { id: 'pricing', title: '5. Prices and service fees', paragraphs: ['Tenant and owner fees are calculated on accommodation rent and recorded for the request. The Tenant Fees page and Owner Fees section display the standard current rates; a specific quote may reflect an applicable owner-specific policy.', 'Deposits, cleaning, utilities and other charges must be separately disclosed where relevant. The full payable amount and payment conditions must be provided before payment.'] },
    { id: 'cancellations-deposits', title: '6. Cancellations, deposits and disputes', paragraphs: ['Review the cancellation and deposit conditions for the particular rental before committing. A listing’s policy label is not a complete refund schedule. The current service has no automated refund, deposit return or dispute-resolution payment process.', 'Contact support with the request reference to raise an issue. No fixed refund percentage, response time or deposit-return deadline is established by this page. Mandatory rights under applicable law remain unaffected.'] },
    { id: 'responsibility', title: '7. Responsibilities and service limits', paragraphs: ['Owners are responsible for supplying the accommodation and accurate listing information. Tenants are responsible for complying with their agreed use, occupancy and property conditions. 32+ is responsible for its own platform service within its actual scope.', 'Availability can be affected by maintenance or technical problems. Nothing here excludes responsibility that cannot lawfully be excluded or replaces any mandatory consumer protection.'] },
    { id: 'questions-changes', title: '8. Questions and changes', paragraphs: ['Use Contact or the operator’s postal address for questions or complaints. Check the terms displayed for your request before proceeding; new information on this page does not by itself rewrite an existing agreement.', 'The governing terms for live payments, detailed cancellation rules and final rental agreements will be supplied before those services are offered.'] },
  ] },
  privacy: { title: 'Privacy Policy', description: 'How personal information is used in the current 32+ service.', legal: true, sections: [
    { id: 'controller', title: '1. Who is responsible', paragraphs: ['Promacan Corp, S.L. operates 32+ and is responsible for personal information processed for its platform services. Its identification and postal address appear below. An owner also receives information needed for a rental and is responsible for their own use of that information.'] },
    { id: 'information', title: '2. Information used', items: ['Account and profile information: name, email, authentication information and any contact information supplied.', 'Rental requests: property, dates, occupants, temporary purpose, decision notes and status.', 'Agreement records: names, signature images, acceptance times and property/request snapshots. Some historic fields may contain address or organisation details supplied earlier.', 'Owner listings: property address, descriptions, photos, availability, calendar links, prices and rental conditions.', 'Saved homes, contact enquiries and technical information needed to serve requests and maintain account sessions.'], paragraphs: ['Do not include health records or other unnecessary sensitive information in temporary-purpose descriptions or contact enquiries. Live payment-card and bank-account collection is not available in the current platform.'] },
    { id: 'purposes', title: '3. Why information is used', paragraphs: ['Account, request and agreement information supports the service you ask for and steps towards a rental agreement. Enquiries are used to respond to the issue raised. Security and abuse-prevention processing supports operation of the platform; records may also be needed to meet applicable obligations or handle claims.', 'The legal basis depends on the specific purpose, including contractual steps, applicable legal obligations or an assessed legitimate interest. Where consent is required, it must be requested for that particular use. A general enquiry is not consent to marketing.'] },
    { id: 'recipients', title: '4. Sharing and service providers', paragraphs: ['Supabase provides the application’s authentication, database and property-image storage. Relevant request and agreement information is made available to the parties through the rental workflow; public listing information and property photos can be viewed by visitors.', 'The website loads Google Fonts, Google Maps on property pages and some images from Unsplash. Requests to these services can disclose technical information such as your IP address. Contact enquiries are accessible to authorised support personnel.', 'Hosting arrangements, the complete processor list and any international-transfer safeguards are being confirmed. Contact the operator for information relevant to your data. No live payment provider is identified as receiving payment information through the current checkout because that checkout is not available.'] },
    { id: 'retention', title: '5. Retention and security', paragraphs: ['Retention depends on the purpose of the record, the status of the account or rental, applicable obligations and any unresolved claim. A category-specific retention schedule is being confirmed; this page does not prescribe an unverified fixed period.', 'Access controls limit access to account and rental records. No system can guarantee absolute security. Do not submit passwords, payment credentials or unnecessary sensitive records in an enquiry.'] },
    { id: 'rights', title: '6. Your rights and enquiries', paragraphs: ['Subject to the applicable conditions, you can request access, correction, erasure, restriction or portability of your data, and object to certain processing. Where processing relies on consent, you can withdraw it without affecting the lawfulness of earlier processing.', 'Contact Promacan Corp, S.L. through Contact or at its postal address below, explaining your request. Proportionate identity confirmation may be needed. You may also complain to the Spanish Data Protection Agency (AEPD).'] },
    { id: 'updates', title: '7. Changes to this information', paragraphs: ['This page describes the current service. Information about new payment, verification or other processing will need to be provided when those features are introduced. See the Cookie Policy for browser storage and embedded services.'] },
  ] },
  cookies: { title: 'Cookie Policy', description: 'Browser storage, account sessions and services loaded by this website.', legal: true, sections: [
    { id: 'storage', title: '1. Cookies and similar storage', paragraphs: ['Cookies and browser local storage can retain information between visits. The current application uses local storage for Supabase authentication sessions and for homes saved by visitors who are not signed in. Local storage is distinct from a cookie but can still affect your privacy.'] },
    { id: 'inventory', title: '2. Storage used by the application', items: ['Supabase session storage: the sb-<project-reference>-auth-token key stores account-session information so you can remain signed in. It is managed by the authentication client and can be removed by signing out or clearing site data.', 'Saved homes: the 32-plus-saved-homes key stores property identifiers for visitors who save homes without signing in. It remains until changed or cleared. Signed-in saved homes are stored in the account database.'], paragraphs: ['No analytics or advertising SDK is configured in the application code reviewed for this page. That does not establish that every deployment or embedded third party is free of cookies.'] },
    { id: 'third-parties', title: '3. Embedded and external services', paragraphs: ['Property pages embed Google Maps. Google Fonts and some Unsplash images are also loaded externally. These requests disclose technical information to their providers, and embedded content may use its own cookies or storage.', 'A complete deployment-level cookie inventory, third-party storage durations and any required consent controls are being confirmed. This page does not claim that non-essential third-party activity is already blocked.'] },
    { id: 'controls', title: '4. Your controls', paragraphs: ['You can review, block or clear cookies and site storage in your browser settings. Clearing authentication storage may sign you out; clearing saved-home storage removes locally saved homes. Blocking third-party content can affect maps, fonts or images.', 'The current application has no cookie-preference panel. Contact the operator with questions about a specific service or storage item.'] },
  ] },
  'legal-notice': { title: 'Legal Notice', description: 'Operator identification and information about use of the 32+ website.', legal: true, sections: [
    { id: 'identification', title: '1. Website operator', paragraphs: ['32+ Night Rentals is operated by Promacan Corp, S.L., CIF B44599611, at Calle Domingo Doreste 23, apartamento 15, 35110 Santa Lucía de Tirajana, Las Palmas, Spain.', 'Use Contact for online enquiries or write to the postal address. Additional corporate registration details are being confirmed.'] },
    { id: 'marketplace', title: '2. Nature of the service', paragraphs: [roles, 'The marketplace concerns furnished accommodation for genuine temporary stays of at least 32 nights. It is not a holiday-rental platform or a traditional long-term letting agency.', verification] },
    { id: 'content', title: '3. Website and listing content', paragraphs: ['Owners supply property information and must keep it accurate and have permission to publish their content. Do not reproduce or misuse content without the appropriate rights. Report inaccurate, unlawful or rights-infringing content through Contact, identifying the material and the reason for the report.', 'External services and links have their own terms and privacy practices. Availability of a link does not guarantee its content.'] },
    { id: 'related-policies', title: '4. Related policies', paragraphs: ['Read the Terms & Conditions for platform use, the Privacy Policy for personal information and the Cookie Policy for browser storage. Specific rental terms are contained in the agreement between the owner and tenant.', 'Nothing in this notice removes any mandatory right or responsibility under applicable law.'] },
  ] },
};
