export type Home={id:string;title:string;location:string;island:string;price:number;bedrooms:number;bathrooms:number;image:string;description:string;features:string[]};
export type PropertyRow={id:string;owner_id:string;title:string;description:string;location:string;island:string;monthly_rent:number;security_deposit:number;cleaning_fee:number;cancellation_policy:string;monthly_prices:Record<string,number>;external_calendar_url:string|null;external_calendar_name:string|null;bedrooms:number;bathrooms:number|string;image_url:string|null;is_published:boolean;minimum_nights:number};
export const homes:Home[]=[
{id:'maspalomas-coast',title:'Light-filled apartment near the coast',location:'Maspalomas, Gran Canaria',island:'Gran Canaria',price:1850,bedrooms:2,bathrooms:1,image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85',description:'A comfortable furnished apartment for a temporary stay, close to the coast and everyday amenities.',features:['Furnished','Fast Wi‑Fi','Terrace','Air conditioning']},
{id:'las-palmas-terrace',title:'Modern island home with terrace',location:'Las Palmas de Gran Canaria',island:'Gran Canaria',price:1650,bedrooms:2,bathrooms:2,image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=85',description:'A bright city home with a private terrace and space to work or settle in for a season.',features:['Furnished','Work desk','Terrace','Washing machine']},
{id:'costa-adeje-ocean',title:'Ocean-view seasonal apartment',location:'Costa Adeje, Tenerife',island:'Tenerife',price:2200,bedrooms:2,bathrooms:2,image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85',description:'A spacious temporary home with ocean views and easy access to the coast.',features:['Furnished','Ocean view','Pool','Air conditioning']},
{id:'arrecife-light',title:'Bright apartment in Arrecife',location:'Arrecife, Lanzarote',island:'Lanzarote',price:1450,bedrooms:1,bathrooms:1,image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85',description:'A compact furnished base for a temporary stay in the island capital.',features:['Furnished','Wi‑Fi','Balcony','Lift']},
{id:'corralejo-sun',title:'Sunny home near Corralejo',location:'Corralejo, Fuerteventura',island:'Fuerteventura',price:1700,bedrooms:2,bathrooms:1,image:'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=85',description:'A relaxed furnished home close to beaches, shops and restaurants.',features:['Furnished','Wi‑Fi','Pool','Parking']},
{id:'puerto-mogan',title:'Quiet apartment in Puerto de Mogán',location:'Puerto de Mogán, Gran Canaria',island:'Gran Canaria',price:1950,bedrooms:2,bathrooms:1,image:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=85',description:'A calm furnished apartment suited to a longer temporary stay in the south-west of Gran Canaria.',features:['Furnished','Balcony','Wi‑Fi','Air conditioning']}];
export const islands=['Canary Islands','Gran Canaria','Tenerife','Lanzarote','Fuerteventura'];
export function getHome(id:string){return homes.find(h=>h.id===id)}
export function propertyToHome(property:PropertyRow):Home{return{id:property.id,title:property.title,location:property.location,island:property.island,price:property.monthly_rent,bedrooms:property.bedrooms,bathrooms:Number(property.bathrooms),image:property.image_url||'/logo.png',description:property.description,features:['Furnished','Minimum 32 nights']}}
