'use client';

import {FormEvent,Suspense,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {Header,Footer} from '../components';
import {homes,islands,Home,propertyToHome,PropertyRow} from '../../lib/data';
import {supabase} from '../../lib/supabase';
import './results.css';

type Filter='pool'|'wifi'|'air'|'beds'|'budget';

function Results(){
  const query=useSearchParams();const initialWhere=query.get('where')||'Canary Islands';
  const[where,setWhere]=useState(initialWhere);const[moveIn,setMoveIn]=useState(query.get('moveIn')||'');const[moveOut,setMoveOut]=useState(query.get('moveOut')||'');const[guests,setGuests]=useState(query.get('guests')||'1');
  const[all,setAll]=useState<Home[]>(homes);const[active,setActive]=useState<Filter[]>([]);const[loading,setLoading]=useState(true);
  useEffect(()=>{supabase.from('properties').select('*').eq('is_published',true).order('created_at',{ascending:false}).then(({data})=>{if(data?.length)setAll((data as PropertyRow[]).map(propertyToHome));setLoading(false)})},[]);
  const filtered=useMemo(()=>all.filter(home=>(where==='Canary Islands'||home.island===where)&&(!active.includes('pool')||home.features.some(feature=>feature.toLowerCase().includes('pool')))&&(!active.includes('wifi')||home.features.some(feature=>feature.toLowerCase().includes('wi')))&&(!active.includes('air')||home.features.some(feature=>feature.toLowerCase().includes('air')))&&(!active.includes('beds')||home.bedrooms>=2)&&(!active.includes('budget')||home.price<=1800)),[all,where,active]);
  function toggle(filter:Filter){setActive(current=>current.includes(filter)?current.filter(item=>item!==filter):[...current,filter])}
  function search(event:FormEvent){event.preventDefault();const params=new URLSearchParams({where,guests});if(moveIn)params.set('moveIn',moveIn);if(moveOut)params.set('moveOut',moveOut);window.history.replaceState(null,'','/homes?'+params)}
  const dateLabel=moveIn&&moveOut?`${shortDate(moveIn)} – ${shortDate(moveOut)}`:'Add dates';

  return <><Header/><main className="results-page"><section className="results-toolbar"><form className="compact-search" onSubmit={search}><label><span>Where</span><select value={where} onChange={event=>setWhere(event.target.value)}>{islands.map(island=><option key={island}>{island}</option>)}</select></label><label className="compact-date"><span>Move in</span><input aria-label="Move in" type="date" value={moveIn} onChange={event=>setMoveIn(event.target.value)}/></label><label className="compact-date"><span>Move out</span><input aria-label="Move out" type="date" value={moveOut} onChange={event=>setMoveOut(event.target.value)}/></label><label><span>Guests</span><select value={guests} onChange={event=>setGuests(event.target.value)}>{[1,2,3,4,5,6].map(number=><option key={number} value={number}>{number} guest{number===1?'':'s'}</option>)}</select></label><button aria-label="Search">⌕</button></form><div className="mobile-search-summary"><b>{where}</b><span>{dateLabel} · {guests} guest{guests==='1'?'':'s'}</span></div><div className="filter-row"><button className="filter-main" onClick={()=>setActive([])}>☷ All filters</button><FilterButton label="Pool" filter="pool" active={active} toggle={toggle}/><FilterButton label="Wi-Fi" filter="wifi" active={active} toggle={toggle}/><FilterButton label="Air conditioning" filter="air" active={active} toggle={toggle}/><FilterButton label="2+ bedrooms" filter="beds" active={active} toggle={toggle}/><FilterButton label="Under €1,800" filter="budget" active={active} toggle={toggle}/></div></section><div className="results-layout"><section className="results-list"><div className="results-heading"><div><p className="eyebrow">FURNISHED SEASONAL RENTALS</p><h1>{loading?'Finding homes…':`${filtered.length} home${filtered.length===1?'':'s'} in ${where}`}</h1><p>Minimum 32 nights · Every stay is subject to owner approval</p></div><button>Sort: Recommended⌄</button></div>{filtered.length?<div className="results-cards">{filtered.map(home=><ResultCard key={home.id} home={home} moveIn={moveIn} moveOut={moveOut}/>)}</div>:<div className="empty-results"><h2>No homes match these filters</h2><p>Try removing a filter or searching another island.</p><button onClick={()=>setActive([])}>Clear filters</button></div>}</section><aside className="results-map" aria-label="Map of Gran Canaria"><iframe title="Map of the Canary Islands" src="https://www.openstreetmap.org/export/embed.html?bbox=-16.1%2C27.55%2C-13.2%2C29.55&amp;layer=mapnik"/><div className="map-label">Map preview</div>{filtered.slice(0,4).map((home,index)=><Link key={home.id} className={`map-price map-price-${index+1}`} href={`/home/${home.id}`}>€{home.price.toLocaleString()}</Link>)}</aside></div></main><Footer/></>;
}

function FilterButton({label,filter,active,toggle}:{label:string;filter:Filter;active:Filter[];toggle:(filter:Filter)=>void}){return <button className={active.includes(filter)?'active':''} onClick={()=>toggle(filter)}>{label}</button>}
function ResultCard({home,moveIn,moveOut}:{home:Home;moveIn:string;moveOut:string}){const params=new URLSearchParams();if(moveIn)params.set('moveIn',moveIn);if(moveOut)params.set('moveOut',moveOut);return <Link className="result-card" href={`/home/${home.id}?${params}`}><div className="result-image" style={{backgroundImage:`url(${home.image})`}}><span className="request-badge">Request only</span><span className="heart" aria-label="Save home">♡</span><div className="image-dots"><i/><i className="selected"/><i/><i/></div></div><div className="result-copy"><div className="result-title"><h2>{home.title}</h2><span>★ New</span></div><p>{home.location}</p><p>{home.bedrooms} bedroom{home.bedrooms===1?'':'s'} · {home.bathrooms} bathroom{home.bathrooms===1?'':'s'}</p><p>{home.features.slice(0,3).join(' · ')}</p><div className="result-price"><strong>€{home.price.toLocaleString()}</strong> monthly <small>· 32+ nights</small></div></div></Link>}
function shortDate(value:string){return new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(new Date(`${value}T12:00:00`))}
export default function HomesPage(){return <Suspense fallback={<main className="loading">Loading homes…</main>}><Results/></Suspense>}
