'use client';

import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {useParams,useSearchParams} from 'next/navigation';
import {Header,Footer} from '../../components';
import {getHome,Home,propertyToHome,PropertyRow} from '../../../lib/data';
import {supabase} from '../../../lib/supabase';

const purposes=['Work / professional assignment','Remote work / temporary professional stay','Study / training','Medical / recovery','Temporary relocation','Home temporarily unavailable','Family / personal temporary circumstances','Other genuine temporary circumstance'];
function nights(moveIn:string,moveOut:string){if(!moveIn||!moveOut)return 0;return Math.round((new Date(`${moveOut}T12:00:00`).getTime()-new Date(`${moveIn}T12:00:00`).getTime())/86400000)}

export default function Property(){
  const{id}=useParams<{id:string}>();const query=useSearchParams();
  const[home,setHome]=useState<Home|null>(null);const[ownerId,setOwnerId]=useState('');const[loading,setLoading]=useState(true);
  const[moveIn,setMoveIn]=useState(query.get('moveIn')||'');const[moveOut,setMoveOut]=useState(query.get('moveOut')||'');
  const[purpose,setPurpose]=useState('');const[details,setDetails]=useState('');const[address,setAddress]=useState('');const[organisation,setOrganisation]=useState('');const[occupants,setOccupants]=useState('1');
  const[confirmed,setConfirmed]=useState(false);const[sent,setSent]=useState(false);const[error,setError]=useState('');const[submitting,setSubmitting]=useState(false);

  useEffect(()=>{async function load(){const{data}=await supabase.from('properties').select('*').eq('id',id).eq('is_published',true).maybeSingle();if(data){setHome(propertyToHome(data as PropertyRow));setOwnerId(data.owner_id)}else setHome(getHome(id)||null);setLoading(false)}load()},[id]);
  if(loading)return <><Header/><main className="loading">Loading home…</main><Footer/></>;
  if(!home)return <><Header/><main className="simple"><h1>Home not found.</h1><Link className="pill" href="/homes">Back to homes</Link></main><Footer/></>;
  const currentHome=home;const stayNights=nights(moveIn,moveOut);

  async function submit(event:FormEvent){event.preventDefault();setError('');if(!ownerId)return setError('This preview listing is not accepting rental requests yet.');if(stayNights<32)return setError('Please select a stay of at least 32 nights.');if(!purpose||!details.trim()||!address.trim())return setError('Please complete all required purpose-of-stay questions.');if(!confirmed)return setError('Please confirm your declaration.');setSubmitting(true);const{data:{user}}=await supabase.auth.getUser();if(!user){setSubmitting(false);window.location.href=`/login?next=${encodeURIComponent(window.location.pathname+window.location.search)}`;return}const{data:profile}=await supabase.from('profiles').select('role').eq('id',user.id).single();if(profile?.role!=='tenant'){setSubmitting(false);return setError('Rental requests must be submitted from a tenant account.')}const{error:insertError}=await supabase.from('rental_requests').insert({property_id:currentHome.id,tenant_id:user.id,owner_id:ownerId,move_in:moveIn,move_out:moveOut,occupants:Number(occupants),purpose_category:purpose,purpose_details:details.trim(),permanent_address:address.trim(),relevant_organisation:organisation.trim()||null,tenant_declaration:true});setSubmitting(false);if(insertError)return setError(insertError.message);setSent(true)}

  return <><Header/><main className="property"><Link className="back" href="/homes">← All homes</Link><div className="property-hero" style={{backgroundImage:`url(${currentHome.image})`}}/><div className="property-grid"><section><div className="location">{currentHome.location}</div><h1>{currentHome.title}</h1><div className="facts"><div><strong>{currentHome.bedrooms}</strong><span> bedrooms</span></div><div><strong>{currentHome.bathrooms}</strong><span> bathrooms</span></div><div><strong>€{currentHome.price.toLocaleString()}</strong><span> / month</span></div></div><p>{currentHome.description}</p><div className="features">{currentHome.features.map(feature=><div key={feature}>✓ {feature}</div>)}</div><p className="form-help">This is a seasonal rental, not a tourist stay or permanent residence. Every stay is subject to the owner&apos;s approval and a signed seasonal rental agreement.</p></section><aside className="enquiry"><h2>Submit rental request</h2>{sent?<div className="notice"><strong>Request submitted.</strong><br/>The owner can now review it. You can follow its status in your dashboard.</div>:<form className="form" onSubmit={submit}><label>Move-in<input required type="date" value={moveIn} onChange={e=>setMoveIn(e.target.value)}/></label><label>Move-out<input required type="date" value={moveOut} onChange={e=>setMoveOut(e.target.value)}/></label>{moveIn&&moveOut&&<div className="stay-length">Stay: <strong>{stayNights} nights</strong></div>}<label>Number of occupants<input required type="number" min="1" value={occupants} onChange={e=>setOccupants(e.target.value)}/></label><label>Purpose of temporary stay<select required value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="">Select a reason</option>{purposes.map(option=><option key={option}>{option}</option>)}</select></label><label>Please explain the temporary purpose<textarea required value={details} onChange={e=>setDetails(e.target.value)} placeholder="Briefly explain why you need temporary accommodation and the expected duration."/></label><label>Permanent home address<textarea required value={address} onChange={e=>setAddress(e.target.value)}/></label><label>Employer, school or relevant organisation (optional)<input value={organisation} onChange={e=>setOrganisation(e.target.value)}/></label><label className="check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I declare that the information supplied is true and that this accommodation is required for a genuine temporary purpose.</span></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={submitting}>{submitting?'Submitting…':'Submit rental request →'}</button></form>}</aside></div></main><Footer/></>;
}
