'use client';

import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {Header,Footer} from '../components';
import {homes,islands,PropertyRow} from '../../lib/data';
import {supabase} from '../../lib/supabase';

type Profile={id:string;role:'tenant'|'owner'|'admin';full_name:string|null};
type RentalRequest={id:string;property_id:string;tenant_id:string;owner_id:string;move_in:string;move_out:string;occupants:number;purpose_category:string;purpose_details:string;permanent_address:string;relevant_organisation:string|null;status:string;created_at:string;properties?:{title:string}|null};

export default function Dashboard(){
  const[profile,setProfile]=useState<Profile|null>(null);const[email,setEmail]=useState('');const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  const[listings,setListings]=useState<PropertyRow[]>([]);const[requests,setRequests]=useState<RentalRequest[]>([]);
  const[title,setTitle]=useState('');const[location,setLocation]=useState('');const[island,setIsland]=useState('Gran Canaria');const[price,setPrice]=useState('');const[bed,setBed]=useState('2');const[image,setImage]=useState('https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85');const[saved,setSaved]=useState('');

  async function refresh(userId:string,role:string){if(role==='owner'||role==='admin'){const[{data:propertyData},{data:requestData}]=await Promise.all([supabase.from('properties').select('*').eq('owner_id',userId).order('created_at',{ascending:false}),supabase.from('rental_requests').select('*, properties(title)').eq('owner_id',userId).order('created_at',{ascending:false})]);setListings((propertyData||[]) as PropertyRow[]);setRequests((requestData||[]) as RentalRequest[])}else{const{data}=await supabase.from('rental_requests').select('*, properties(title)').eq('tenant_id',userId).order('created_at',{ascending:false});setRequests((data||[]) as RentalRequest[])}}
  useEffect(()=>{async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}setEmail(user.email||'');const{data,error:profileError}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(profileError){setError(profileError.message);setLoading(false);return}setProfile(data as Profile);await refresh(user.id,data.role);setLoading(false)}load()},[]);

  async function add(event:FormEvent){event.preventDefault();if(!profile)return;setError('');const{error:addError}=await supabase.from('properties').insert({owner_id:profile.id,title,location,island,monthly_rent:Number(price),bedrooms:Number(bed),bathrooms:1,image_url:image,description:'Furnished seasonal home listed by an owner.',is_published:true,minimum_nights:32});if(addError)return setError(addError.message);setTitle('');setLocation('');setPrice('');setSaved('Listing published.');await refresh(profile.id,profile.role)}
  async function importHomes(){if(!profile)return;setError('');const rows=homes.map(home=>({owner_id:profile.id,title:home.title,description:home.description,location:home.location,island:home.island,monthly_rent:home.price,bedrooms:home.bedrooms,bathrooms:home.bathrooms,image_url:home.image,is_published:true,minimum_nights:32}));const{error:importError}=await supabase.from('properties').insert(rows);if(importError)return setError(importError.message);setSaved('Starter homes are now live.');await refresh(profile.id,profile.role)}
  async function decide(requestId:string,status:'approved'|'declined'){if(!profile)return;setError('');const{error:updateError}=await supabase.rpc('owner_decide_rental_request',{p_request_id:requestId,p_approve:status==='approved',p_note:null});if(updateError)return setError(updateError.message);await refresh(profile.id,profile.role)}
  async function accept(requestId:string){if(!profile)return;setError('');const{error:acceptError}=await supabase.rpc('tenant_accept_approved_request',{p_request_id:requestId});if(acceptError)return setError(acceptError.message);await refresh(profile.id,profile.role)}

  if(loading)return <><Header/><main className="loading">Loading dashboard…</main><Footer/></>;
  if(!profile)return <><Header/><main className="simple"><h1>Your dashboard</h1><p className="lead">Sign in to manage your account and rental requests.</p><Link className="pill" href="/login">Sign in</Link>{error&&<div className="error">{error}</div>}</main><Footer/></>;
  if(profile.role==='tenant')return <><Header/><main className="page"><p className="eyebrow">TENANT DASHBOARD</p><h1>Rental requests</h1><p className="muted">{email}</p>{error&&<div className="error">{error}</div>}<section className="panel">{requests.length?requests.map(request=><RequestCard key={request.id} request={request} onAccept={accept}/>):<><p>You have not submitted a rental request yet.</p><Link className="pill" href="/homes">Find a home</Link></>}</section></main><Footer/></>;

  return <><Header/><main className="page"><p className="eyebrow">OWNER DASHBOARD</p><h1>Welcome back.</h1><p className="muted">{email}</p>{error&&<div className="error">{error}</div>}{saved&&<div className="notice">{saved}</div>}<div className="dashboard-grid"><section className="panel"><h2>Your homes</h2>{listings.length?listings.map(home=><div className="listing-row" key={home.id}><img src={home.image_url||'/logo.png'} alt=""/><div><strong>{home.title}</strong><div className="muted">€{home.monthly_rent.toLocaleString()} / month · {home.location}</div><Link className="card-link" href={`/home/${home.id}`}>View listing →</Link></div></div>):<div><p className="muted">No database listings yet.</p><button className="primary import-button" onClick={importHomes}>Publish the 6 starter homes</button></div>}<h2 style={{marginTop:35}}>Add a listing</h2><form className="form" onSubmit={add}><label>Property title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Location<input required value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Island<select value={island} onChange={e=>setIsland(e.target.value)}>{islands.slice(1).map(i=><option key={i}>{i}</option>)}</select></label><label>Monthly price<input required type="number" min="1" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Bedrooms<input required type="number" min="1" value={bed} onChange={e=>setBed(e.target.value)}/></label><label>Image URL<input required type="url" value={image} onChange={e=>setImage(e.target.value)}/></label><button className="primary">Publish listing</button></form></section><aside className="panel"><h2>Rental requests</h2>{requests.length?requests.map(request=><RequestCard key={request.id} request={request} owner onDecide={decide}/>):<p className="muted">No rental requests yet.</p>}</aside></div></main><Footer/></>;
}

function RequestCard({request,owner=false,onDecide,onAccept}:{request:RentalRequest;owner?:boolean;onDecide?:(id:string,status:'approved'|'declined')=>void;onAccept?:(id:string)=>void}){const[confirmed,setConfirmed]=useState(false);return <div className="request-card"><strong>{request.properties?.title||'Seasonal home'}</strong><p>{request.move_in} → {request.move_out} · {request.occupants} occupant{request.occupants===1?'':'s'}</p><p><strong>Purpose:</strong> {request.purpose_category}</p><p>{request.purpose_details}</p><span className="status">{request.status.replace('_',' ')}</span>{owner&&request.status==='submitted'&&<div className="actions"><button className="primary-small" onClick={()=>onDecide?.(request.id,'approved')}>Approve request</button><button onClick={()=>onDecide?.(request.id,'declined')}>Decline</button></div>}{request.status==='approved'&&owner&&<p className="form-help">Approved and recorded. The tenant can now accept the approved rental details.</p>}{request.status==='approved'&&!owner&&<div className="acceptance"><label className="check"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/><span>I have reviewed and accept the approved property, dates and purpose-of-stay details.</span></label><button className="primary-small" disabled={!confirmed} onClick={()=>onAccept?.(request.id)}>Accept approved terms</button><p className="form-help">A lawyer-approved seasonal rental document must be added before this can serve as the final legal e-signature.</p></div>}{request.status==='tenant_signed'&&<p className="form-help">Tenant acceptance recorded. Payment setup is the next step.</p>}</div>}
